name: Remove a Label when Closed Pull Request
on:
  pull_request:
    types: [closed]

jobs:
  remove-label:
    runs-on: ubuntu-latest
    steps:
      - name: 「レビュー依頼中」ラベルの除去
        uses: actions/github-script@v7
        continue-on-error: true # ラベルが付いてない場合はエラーになるが無視する
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              name: 'レビュー依頼中',
            });
